// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yoqeaqmatowilhhsubfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlvcWVhcW1hdG93aWxoaHN1YmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3Nzc1NjYsImV4cCI6MjA3MzM1MzU2Nn0.3lHTy8t79nC9ycA-TlaS3qhM-RVG1ki8eJslrBHxVM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});